# Ref for actions.yml
# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

name: 'Envkeeper Actions'
description: 'Check and purge inactive Environments'
author: 'hwakabh'

inputs:
  repo:
    description: "Repository to operate"
    required: true
    default: ${{ github.repository }}
  token:
    description: "GitHub Personal Access Token for the actions"
    required: true
    default: ${{ github.token }}

outputs:
  results:
    description: "Output result placeholder"
    value: "${{ steps.context.outputs.action-result }}"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        repository: hwakabh/envkeeper

    - name: Setup Python
      uses: actions/setup-python@v6
      with:
        python-version-file: '.python-version'

    - name: Install envkeeper CLI
      shell: bash
      run: pip install envkp

    # Pass action inputs to CLI
    - name: Run envkp
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
      run: |
          envkp --repo=${{ inputs.repo }} clean

branding:
  icon: 'file'
  color: 'white'
