# Ref for actions.yml
# https://docs.github.com/en/actions/sharing-automations/creating-actions/metadata-syntax-for-github-actions

name: 'Envkeeper Actions'
description: 'Check and purge inactive Environments'
author: 'hwakabh'

inputs:
  repo:
    description: "Repository to operate"
    required: true
    default: ${{ github.repository }}
  token:
    description: "GitHub Personal Access Token for the actions"
    required: true
    default: ${{ github.token }}

outputs:
  results:
    description: "Output result placeholder"
    value: "${{ steps.context.outputs.action-result }}"

runs:
  using: "composite"
  steps:
    - uses: checkout?
      if: steps.action_black.outputs.is_formatted == 'true'
      with:
        tool_name: blackfmt
        fail_on_error: true

    - uses: setup-python?

    - id: context
      shell: bash
      run: |
          echo "action-result=${{ inputs.param1 }}" >> $GITHUB_OUTPUT

branding:
  icon: 'file'
  color: 'white'
