name: Build Container Image

on:
  # push:
  #   branches:
  #     - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  publish:
    name: Build and Push container image
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pack
        uses: buildpacks/github-actions/setup-pack@v5.8.8

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build application images
        run: |
          pack build ghcr.io/hwakabh/envkp:latest \
            --buildpack paketo-buildpacks/python \
            --builder paketobuildpacks/builder-jammy-base \
            --path . \
            --verbose \
            --clear-cache \
            --publish
