name: Python Package Release

on:
  # for testings
  pull_request:
  workflow_dispatch:
  # push:
  #   tags:
  #     - '*'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-24.04
    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/envkp

    steps:
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: '__token__'
          password: ${{ secrets.PYPI_TOKEN }}
