name: Test PR Changes

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  test-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pack
        uses: buildpacks/github-actions/setup-pack@v5.9.4

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version-file: '.python-version'

      - name: Install envkeeper CLI
        shell: bash
        run: |
          pip install envkp

      - name: Export as deps
        shell: bash
        run: |
          pip freeze > requirements.txt

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build application images
        run: |
          pack build ghcr.io/hwakabh/envkp:latest \
            --buildpack paketo-buildpacks/python \
            --builder paketobuildpacks/builder-jammy-base \
            --default-process entrypoint \
            --env BP_CPYTHON_VERSION=$(cat .python-version) \
            --path . \
            --verbose \
            --clear-cache
